In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [8]:
import numpy as np
from numpy import linalg as la

def matrix_input(rows_of_mat_a,cols_of_mat_a,mat_a):
    #Taking the input values of matrix A
    for i in range(0,rows_of_mat_a):
        temp = []
        for j in range(0,cols_of_mat_a):
            print("please enter a number into the matrix positioned "+ str(i) +"th row and "+ str(j) +"th column")
            val = int(input())
            temp.append(val)
        mat_a.append(temp)

    print(mat_a)
    return


#Taking the dimensions of the matrices
rows_of_mat_a,cols_of_mat_a  = int(input("Please enter the no. of rows of matrix A : ")),int(input("Please enter the no. of columns of matrix  A : "))

mat_a,result = [],[] # intializing the mat_a to null.

# matrix_input(rows_of_mat_a,cols_of_mat_a,mat_a) # taking the matrix input through a function.
mat_a = np.array([[1,2],[3,4]])
eigen_values, eigen_vectors = la.eig(mat_a)
print("Eigen_values for the given Matrix is :",eigen_values)
print("Eigen_vectors for the given Matrix is :",eigen_vectors)

Please enter the no. of rows of matrix A : 2
Please enter the no. of columns of matrix  A : 2
please enter a number into the matrix positioned 0th row and 0th column
0
please enter a number into the matrix positioned 0th row and 1th column
2
please enter a number into the matrix positioned 1th row and 0th column
2
please enter a number into the matrix positioned 1th row and 1th column
3
[[0, 2], [2, 3]]
Eigen_values for the given Matrix is : [-1.  4.]
Eigen_vectors for the given Matrix is : [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [15]:
# call numpy transposes
# Normalise - divide each vector by its norm.
mat_a = np.array([[1,2],[3,4]])
A_ApowerT = np.dot(mat_a,mat_a.transpose())
ApowerT_A = np.dot(mat_a.transpose(),mat_a)
print(A_ApowerT,ApowerT_A)


[[ 5 11]
 [11 25]] [[10 14]
 [14 20]]


In [17]:
#non-square matrix
a = np.array([[1,2,3], [4,5,6]])
# Using SVD
u, s, r = np.linalg.svd(a)
# Singular values
singular_values = s
# Left singular vectors : eigen values of A and A transpose
left_singular_vectors = u
# Right singular vectors : eigen values of A transpose and A
right_singular_vectors = r.transpose()

print("Singular Values(lambda):",singular_values)
print("\nLeft Singular Vectors(U):",'\n',left_singular_vectors)
print("\nRight Singular Vectors(VTrans):",'\n',right_singular_vectors)


Singular Values(lambda): [9.508032   0.77286964]

Left Singular Vectors(U): 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

Right Singular Vectors(VTrans): 
 [[-0.42866713  0.80596391  0.40824829]
 [-0.56630692  0.11238241 -0.81649658]
 [-0.7039467  -0.58119908  0.40824829]]
